## First half

In [1]:
import numpy as np
import pandas as pd

from scipy import stats
import json

In [2]:
def read_beboc_results(path):
    df = pd.DataFrame([])
    for fold in range(5):
        with open(path+str(fold)+'.json', 'r') as f:
            fold_results = json.load(f)
        for tag in fold_results.keys():
            if tag not in df.index:
                df['label'] = list(fold_results.keys())
                df.set_index('label', drop=True, inplace=True)
            df.loc[tag, fold] = fold_results[tag]['f1']
    df['mean'] = df.mean(axis=1)
    df['std'] = df.std(axis=1)
    return df

In [3]:
read_beboc_results('New_results/beboc_5folds_half_train_first/BEboC-5fold_tag_results_fold')

              0         1         2         3         4      mean       std
label
ORG    0.469873  0.489272  0.466106  0.497101  0.497773  0.484025  0.013482
LOC    0.485308  0.468347  0.449212  0.440710  0.453625  0.459440  0.015733
PER    0.430249  0.441748  0.483650  0.453333  0.454472  0.452690  0.017807

In [6]:
def read_bebic_results(path):
    df = pd.DataFrame([])
    for fold in range(5):
        with open(path+str(fold)+'.json', 'r') as f:
            fold_results = json.load(f)
        best_mean_f1 = 0
        best_epoch = 0
        for i, f1s in enumerate(zip(fold_results['ORG']['f1'], fold_results['LOC']['f1'], fold_results['PER']['f1'])):
            mean_f1 = np.mean(f1s)
            if mean_f1 > best_mean_f1:
                best_mean_f1 = mean_f1
                best_epoch = i
        for tag in fold_results.keys():
            if tag not in df.index:
                df['label'] = list(fold_results.keys())
                df.set_index('label', drop=True, inplace=True)
            df.loc[tag, fold] = fold_results[tag]['f1'][best_epoch]
    df['mean'] = df.mean(axis=1)
    df['std'] = df.std(axis=1)
    return df

In [7]:
read_bebic_results('New_results/bebic_5folds_half_train_first/BEbiC-5fold_head_results_fold')

              0         1         2         3         4      mean       std
label
ORG    0.916420  0.904187  0.918838  0.917073  0.912890  0.913882  0.005218
LOC    0.938395  0.948311  0.946421  0.931373  0.949957  0.942891  0.006995
PER    0.945934  0.944274  0.947947  0.939665  0.377038  0.830972  0.226983

#### Новые данные

In [8]:
read_bebic_results('New_results/bebic_5folds_half_train_first/BEbiC-5fold_head_results_fold')

              0         1         2         3         4      mean       std
label
ORG    0.916420  0.904187  0.918838  0.917073  0.927253  0.916754  0.007385
LOC    0.938395  0.948311  0.946421  0.931373  0.839344  0.920769  0.041158
PER    0.945934  0.944274  0.947947  0.939665  0.948630  0.945290  0.003203

Мде